### ISSUE TITLE
Can't parse a bit complex toml file

### ISSUE THREAD

**Issue by xmonader** [crystal-community/toml.cr#24]
I've a problem parsing a bit complex toml file (parsing it in python works fine).
The following file contains the config.toml example and  the crystal test file.
I tried https://github.com/crystal-community/toml.cr and https://github.com/Stygmates/crystal-toml

```
Unhandled exception: expected hardware_types to be an Array, not {"amd" => {"name" => "amd"}} at 20:17 (TOML::ParseException)
  from lib/toml/src/toml/parser.cr:284:7 in 'raise'
  from lib/toml/src/toml/parser.cr:153:11 in 'parse_array_table_header'
  from lib/toml/src/toml/parser.cr:95:14 in 'parse_table_header'
  from lib/toml/src/toml/parser.cr:26:9 in 'parse'
  from lib/toml/src/toml/parser.cr:4:5 in 'parse'
  from lib/toml/src/toml.cr:11:5 in 'parse'
  from test.cr:3:1 in '__crystal_main'
  from ../../../../../../usr/share/crystal/src/crystal/main.cr:105:5 in 'main_user_code'
  from ../../../../../../usr/share/crystal/src/crystal/main.cr:91:7 in 'main'
  from ../../../../../../usr/share/crystal/src/crystal/main.cr:114:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

[example.zip](https://github.com/crystal-community/toml.cr/files/4902062/example.zip)

```toml
[inputSimulatorConfig]
hws = ["amd_starter","amd_big"]
growth_values = [50000, 200000, 1000000]
token_prices = [0.15, 0.3, 3.0]
cloudunits_price_ranges = [3]
export_path = ""

[interpolation]
cpr_improve = "0:0,60:40"
cpr_sales_price_decline = "0:0,60:40"
utilization = "20:80,40:90"
token_price = ""
cost_rack_unit = ""
cost_power_kwh = ""

[hardware_types]
[hardware_types.amd]
name = "amd"

[[hardware_types.amd.components]]
name = "margin1"
description = "Margin per node for threefold and its partners"
cost = 400.0
power = 0
rackspace_u = 0.0
cru = 0.0
sru = 0.0
hru = 0.0
mru = 0.0
su_perc = 0.0
cu_perc = 0.0
link = ""
passmark = 0
[[hardware_types.amd.components]]
name = "margin2"
description = "margin per node for threefold and its partners"
cost = 900.0
power = 0
rackspace_u = 0.0
cru = 0.0
sru = 0.0
hru = 0.0
mru = 0.0
su_perc = 0.0
cu_perc = 0.0
link = ""
passmark = 0

[[hardware_types.amd.components]]
name = "chassis"
description = "Chassis for Ryzen CPU (no cpu inside), 4 HD slots, 1 SSD slots, 10 gbit nic"
cost = 300.0
power = 30
rackspace_u = 2.0
cru = 0.0
sru = 0.0
hru = 0.0
mru = 0.0
su_perc = 0.0
cu_perc = 0.0
link = ""
passmark = 0

[[hardware_types.amd.components]]
name = "hd8"
description = "Seagate Baracuda 8TB (6-8 watt)"
cost = 200.0
power = 10
rackspace_u = 0.0
cru = 0.0
sru = 0.0
hru = 8000.0
mru = 0.0
su_perc = 100.0
cu_perc = 0.0
link = ""
passmark = 0

[[hardware_types.amd.components]]
name = "hd12"
description = "Seagate Baracuda 12TB (6-8 watt)"
cost = 330.0
power = 10
rackspace_u = 0.0
cru = 0.0
sru = 0.0
hru = 12000.0
mru = 0.0
su_perc = 100.0
cu_perc = 0.0
link = ""
passmark = 0

[[hardware_types.amd.components]]
name = "amd1"
description = "AMD Ryzen 3 3600X (12 logical cores)"
cost = 240.0
power = 80
rackspace_u = 0.0
cru = 12.0
sru = 0.0
hru = 0.0
mru = 0.0
su_perc = 0.0
cu_perc = 100.0
link = ""
passmark = 18000

[[hardware_types.amd.components]]
name = "amd2"
description = "AMD Ryzen 7 3800X (16 logical cores)"
cost = 377.0
power = 105
rackspace_u = 0.0
cru = 16.0
sru = 0.0
hru = 0.0
mru = 0.0
su_perc = 0.0
cu_perc = 100.0
link = ""
passmark = 24500

[[hardware_types.amd.components]]
name = "ssd05"
description = "0.5 TB SSD"
cost = 120.0
power = 5
rackspace_u = 0.0
cru = 0.0
sru = 500.0
hru = 0.0
mru = 0.0
su_perc = 100.0
cu_perc = 0.0
link = ""
passmark = 0

[[hardware_types.amd.components]]
name = "ssd1"
description = "1 TB SSD"
cost = 240.0
power = 5
rackspace_u = 0.0
cru = 0.0
sru = 1000.0
hru = 0.0
mru = 0.0
su_perc = 100.0
cu_perc = 0.0
link = ""
passmark = 0

[[hardware_types.amd.components]]
name = "mem16_ddr4"
description = "mem 16GB"
cost = 140.0
power = 8
rackspace_u = 0.0
cru = 0.0
sru = 0.0
hru = 0.0
mru = 16.0
su_perc = 0.0
cu_perc = 100.0
link = ""
passmark = 0

[[hardware_types.amd.components]]
name = "mem32_ddr4"
description = "mem 32GB"
cost = 220.0
power = 10
rackspace_u = 0.0
cru = 0.0
sru = 0.0
hru = 0.0
mru = 32.0
su_perc = 0.0
cu_perc = 100.0
link = ""
passmark = 0

[[hardware_types.amd.components]]
name = "mem64_ddr4"
description = "mem 64GB"
cost = 400.0
power = 16
rackspace_u = 0.0
cru = 0.0
sru = 0.0
hru = 0.0
mru = 64.0
su_perc = 0.0
cu_perc = 100.0
link = ""
passmark = 0

[[hardware_types.amd.components]]
name = "ng2"
description = "48 ports 10 gbit + 4 ports 10 gbit sfp: fs.com + cables"
cost = 4500.0
power = 100
rackspace_u = 1.0
cru = 0.0
sru = 0.0
hru = 0.0
mru = 0.0
su_perc = 0.0
cu_perc = 0.0
link = ""
passmark = 0

[[hardware_types.amd.devices]]
name = "amd_starter"
[[hardware_types.amd.devices.components]]
name = "chassis"
nr = 1

[[hardware_types.amd.devices.components]]
name = "amd1"
nr = 1

[[hardware_types.amd.devices.components]]
name = "hd8"
nr = 1

[[hardware_types.amd.devices.components]]
name = "mem32_ddr4"
nr = 1

[[hardware_types.amd.devices.components]]
name = "ssd05"
nr = 1

[[hardware_types.amd.devices.components]]
name = "margin1"
nr = 1


[[hardware_types.amd.devices]]
name = "amd_big"
[[hardware_types.amd.devices.components]]
name = "chassis"
nr = 1

[[hardware_types.amd.devices.components]]
name = "amd2"
nr = 1

[[hardware_types.amd.devices.components]]
name = "hd12"
nr = 4

[[hardware_types.amd.devices.components]]
name = "mem64_ddr4"
nr = 2

[[hardware_types.amd.devices.components]]
name = "ssd1"
nr = 1

[[hardware_types.amd.devices.components]]
name = "margin2"
nr = 1


[[hardware_types.amd.devices]]
name = "switch"
[[hardware_types.amd.devices.components]]
name = "ng2"
nr = 1



[hardware]

[hardware.amd_big]
name = "amd_big"
hardware_type = "amd"
[[hardware.amd_big.nodes]]
name = "compute"
template = "amd_big"
nr = 20
[[hardware.amd_big.overhead]]
name = "switch"
template = "swtich"
nr = 2


[hardware.amd_starter]
name = "amd_starter"
hardware_type = "amd"
[[hardware.amd_starter.nodes]]
name = "compute"
template = "amd_starter"
nr = 1



```

crystal code

```
require "toml"

h = TOML.parse(File.read("config.toml")).as(Hash)
puts h.inspect
```
